### PR TITLE
Update boostrap to 4.1.1

### PR DESCRIPTION
**Pull request by adawalli**
Updating boostrap required pulling in popper.js (which
required adding sync-exec as a dev dependency). Some
of the templates were updated based on changes from
bootstrap.

Signed-off-by: Adam Wallis <adam.wallis@gmail.com>

### CODE REVIEW

**Comment by adawalli** [comment]
@sloria, @dasdachs - Can you take a look and let me know if any improvements are needed?

**Comment by dasdachs** [comment]
@adawalli thank you! Great job! 

Just a personal preference: since bootstrap 4 removed `btn-default`, I'd replace it with `btn-light` not `btn-primary`. 



But it's your and @sloria 's call.

**Comment by sloria** [comment]
This is great! Thanks for this @adawalli .

I few minor suggestions.

The featurette buttons should be de-emphasized. There should only be one call to action on a page. I think `btn-outline-secondary` works well.

my flask app 2018-06-20 07-51-05

The jumbotron should take up the entire width (no whitespace on the sides).

my flask app 2018-06-20 07-52-00

Check out the jumbotron template in the docs: https://getbootstrap.com/docs/4.1/examples/jumbotron/

There isn't enough margin around the sign-up form:

my flask app 2018-06-20 07-52-45

Does it have the proper container classes around it?

None of these are hard blockers to merge. Let me know if you don't have time to do them, and I can fix them up when I have some time.

**Comment by adawalli** [comment]
Thanks for the feedback @dasdachs 

@sloria, I will definitely take a look at your comments and work on fixing them up soon. Thanks!

**Comment by adawalli** [comment]
if you want to finish this out, I would be grateful. I am not going to get to it like I had thought

**Comment by sloria** [comment]
No problem. I've marked this one as 'help wanted'. I don't have time to work on this right now, but hopefully someone else can pick this up.

Thanks again for taking this on!

**Comment by Hiyorimi** [comment]
Let me know if there is anything else I can do to help with the migration.

**Comment by sloria** [comment]
@Hiyorimi Thanks for continuing work on this! Would you mind resolving the merge conflict?

**Comment by Hiyorimi** [comment]
Github suggests that `Only those with write access to this repository can merge pull requests.`

**Comment by Hiyorimi** [comment]
Fixed in #359.

**Comment by sloria** [comment]
OK, let's carry this on in #359.

**Pull request closed without merging**
