### PR TITLE
Bootstrap4

### PR DESCRIPTION
**Pull request by Hiyorimi**
Fixed jumbotron spacing, btn-outline-secondary and about.html, register.html issues.

### CODE REVIEW

**Comment by sloria** [comment]
This is looking great!

There seems to be a spacing/sizing issue with the header and alerts. I see the following after registering:

image

**Comment by sloria** [comment]
The above is not an issue on the `/users/` page.

image

It only happens on the home page, such as when you register or log out:

image

**Comment by Hiyorimi** [comment]
It was a login form issue, fixed it, also renamed button, since it makes more sense now.

**Comment by sloria** [comment]
Thanks for looking into that @Hiyorimi . 

It's still not 100% correct--the alert has unnecessary spacing around it:

image

The alert should also take the whole width.

**Expected**

(this is what it was before 66b97d5)

image

**Actual**

image

**Comment by Hiyorimi** [comment]
Since the cross is stretched to far to the right, I took the responsibility to wrap alerts in the container, to make it more neat IMO.

If spacing still seems unnecessary, I can remove it.

**Comment by sloria** [comment]
The alerts should align with the full width (as in the "Expected" screenshot above).

**Comment by Hiyorimi** [comment]
Any news ?

**Pull request merged**
