### PR TITLE
Added Pipfile and updated {{{cookiecutter.app_name}}/README.rst

### PR DESCRIPTION
**Pull request by dasdachs**
I added a `Pipfile` if someone wishes to use `pipenv` instead of `pip`. 

The package versions were not altered, the `Pipfile` is composed out of `prod.txt` and `dev.txt`

### CODE REVIEW

**Comment by sloria** [comment]
Excellent!

I don't think a project should have both requirements.txt and Pipfile. Could you look into cookiecutter's hooks to allow users to conditionally use one or the other?

**Comment by dasdachs** [comment]
@sloria I updated the README.rst to point to either `pipenv`or `pip` and added a post_get hook that removes either the `Pipfile`or the requirements files.

**Comment by sloria** [comment]
Looks great!

**Comment by sloria** [comment]
By the way, I'm starting to use something along the lines of the [Pull Request Hack](http://felixge.de/2013/03/11/the-pull-request-hack.html). Basically, if you get a PR merged in, you get an invite to have commit access.

No pressure to do any more work than you already have. Just want to open the door to further collaboration. =)

**Pull request merged**
